### ISSUE TITLE
Inaccurate Gaster Blaster Sounds.

### ISSUE THREAD

**Issue by Combine12** [Jcw87/c2-sans-fight#1]
The Gaster Blaster sounds in the current version of this are not correct.

Since the Gaster Blaster noise ingame is made up of two sounds that have their speed altered, i've recreated the sound and merged it into a single OGG file:

https://u.pomf.is/rlesev.ogg

**Comment by Jcw87** [comment]
I've been waiting to verify this before responding, but I haven't had the time. If there is a second sound being mixed in, I would rather just stick in the original sounds, and pitch shift/mix them at runtime. I would also prefer to convert the original sound myself, so if you want to help, you can tell me the filename of the other extracted sound. (example: 00002a00.wav)

**Comment by Combine12** [comment]
Ah, alright then. The sounds are 00002a29.wav and 00002a30.wav, and both are sped up by approximately 20 percent.

**Comment by Jcw87** [comment]
The other sound has now been added.
