### ISSUE TITLE
2 attacks at once

### ISSUE THREAD

**Issue by Sans15Undertale15** [Jcw87/c2-sans-fight#10]
I was fooling around, and I wasn't paying attention, so I missed an attack, then I hit him also.
That displayed 2 functional attacks, making me die, and finding something interesting to tell you!

Happy Camping,
Sans15Undertale15,
OUT!

**Comment by Jcw87** [comment]
I had a look at the code and saw a frame-perfect case where this could occur. I've re-arranged it so that the miss check is done first, as missing will lock you out of hitting.

84dc060f7fcafbbb6062d31aa829291e69961e24

**Comment by OffifialMITX** [comment]
Maybe you should take a look at [this](https://drive.google.com/open?id=0B8HcTODSY2Xzanl0cWs3OXBpYnM), its when I hit outside the box and continue to press **[Z]** and / or **[ENTER]**.

**Comment by Jcw87** [comment]
Spotted the problem. It would seem that while fixing this this issue in January, I had forgotten about a _different_ frame-perfect case that I had originally taken into consideration when I first programmed it. The new arrangement of the code should *really* fix it this time.

**Comment by OffifialMITX** [comment]
Actually, it's rather very fun than a problem, for me at least. That leads me to the thought, maybe random generated attacks would be a good and easy feature to implement, what do you think?

P.S. The attacks don't have to be neccesaryly dodgeable.
