### ISSUE TITLE
BoneV/HRepeat functions

### ISSUE THREAD

**Issue by deel72** [Jcw87/c2-sans-fight#106]
Can't change bone color (blue, orange) when using BoneV/HRepeat function.
Also would be cool if there was color changing feature for bonestabs. Sorry if i'm bothering you too much

**Comment by Jcw87** [comment]
BoneHRepeat and BoneVRepeat were added for convenience. The original fight only ever had single blue bones, so color was never added to these. I have no plans to extend these functions. If anything, they would get removed if I ever get around to replacing the CSV attack system with some sandboxed JavaScript, as it would then be trivial to implement these yourself.
