### ISSUE TITLE
Kinda cheating

### ISSUE THREAD

**Issue by OffifialMITX** [Jcw87/c2-sans-fight#11]
You can easily dodge the bonestab attack by simply pressing all arrow buttons every time he throws you.

However, I'm not sure if it should be removed since you can basically do the same thing in the original game - even better - in the original you have to press it only once during the whole part.

**Comment by Jcw87** [comment]
Any attempt at preventing that would likely just cause more issues. It's not worth the headache to try stopping people from doing that. Stopping people from just holding all the arrows was easy though, and I don't intend on unfixing that. The cheese was too great.
