### ISSUE TITLE
This isnt an issue but

### ISSUE THREAD

**Issue by Ringi0911** [Jcw87/c2-sans-fight#124]
WHERE THE FLYING FUCK IS THE HTML FILE
im not an expert in construct sorry

**Comment by ChaboCode** [comment]
Construct doesn’t work by html files, it has its own files to use in the editor. They are in an xml format so you better don’t edit them by hand. When the game is ready Construct makes a build that has the actual web code you see in the browser

**Comment by Ringi0911** [comment]
I closed it immediately because I realized that cause i used to work on construct
Thanks anyways though
