### ISSUE TITLE
Final attack timing is incorrect

### ISSUE THREAD

**Issue by OffifialMITX** [Jcw87/c2-sans-fight#14]
Sans just [threw me into a Gaster Blaster](https://drive.google.com/file/d/0B8HcTODSY2XzZXdTUGNiUGQwSmM/view?usp=sharing)... LOL.

**Comment by FawfulBeanish** [comment]
You can actually dodge the attack if you start from the bottom right instead of doing what you did. I'm pretty sure this is in the original game too.

**Comment by OffifialMITX** [comment]
Oh, yes, knda noticed already, forgot the issue. Guess we don't have to keep it open then, do we?

**Comment by Jcw87** [comment]
I've never tried doing what you did in the original game, nor have seen any videos where someone did that. My assumption is that the original game will do this too, if you approach it the same way. If I was still actively working on this, I would test it. But, I'm not, and also, I'm lazy. If you can prove that the original game behaves differently in this situation, I'll consider changing it. Otherwise, it will stay as is.

**Comment by OffifialMITX** [comment]
I assume that the original game would do the same and this was rather funny then confusing anyway.

The next time I could be able to try this out is the next summer and you can do a no hit run so I guess it doesn't matter for now.

Besides I have some videos of dodging attacks in a way you couldn't if the hit box's size were correct, wanna see?

**Comment by Jcw87** [comment]
Not really. I know the hitbox sizes are wrong, but until I know what the right sizes are, I'm not changing them. It's really hard to judge the size of the hitboxes from videos, as both objects involved are moving, and there may or may not be a 1 frame delay between the hit being registered and any visual feedback from it.

I tried approximating the player hitbox once, but it made the gaster blasters from the first attack unavoidable. Keeping it as it is now is preferable to that.

**Comment by OffifialMITX** [comment]
ALRIGHT... I had enough insanity to  survive the final attack with one HP to prove this, and... it did [exactly the same thing](https://drive.google.com/open?id=0B8HcTODSY2XzZTFSSXBsblJfbzg). I guess that means we can close this issue.
