### ISSUE TITLE
Consider mirroring the repos to Codeberg

### ISSUE THREAD

**Issue by throwaway-d** [Jcw87/c2-sans-fight#142]
Please consider mirroring repos to Codeberg because:
1. Codeberg is libre, free, open-source, privacy-friendly, non-profit, really fast
2. GitHub has bloated interface with captcha & GitHub is privacy-invasive, Microsoft-owned, proprietary, vendor-lock-in, Tor-hostile
3. People on Codeberg like me can contribute to the project
4. GitHub can take down our repos

Here are some sources for you written by me: https://codeberg.org/Recommendations/Mirror_to_Codeberg

**Comment by Jcw87** [comment]
This repository doesn't get enough activity to warrant mirroring to anywhere. Also, most open-source projects I have ever needed to clone were on GitHub, and not a single one was on Codeberg. They don't seem to share your concerns. I have never heard of Codeberg until just now. Additionally, you seem to be mass-posting on repositories, which is too spambot-like for my taste.

**Comment by throwaway-d** [comment]
> too spambot-like for my taste.

OK. That is also why some repos ignored me and closed the issues without any explanation even if I asked why. At least you explained! :)

> mass-posting on repositories

They are the projects that I personally use.
