### ISSUE TITLE
Sans needs to repeat his last attack IF Chara ate something.

### ISSUE THREAD

**Issue by TurtMaster2000** [Jcw87/c2-sans-fight#152]
This needs to happen. I know that it makes it harder, but part of this is to practice and whatnot so it is completely necessary. It could also help to make a mode to where it is just like where it is now, (where it doesn't repeat at all). Hope this can be easy to implement so good luck!

**Comment by Jcw87** [comment]
The goal of "normal mode" is to replicate how the fight works in Undertale. What you have described is not how Undertale works. I did a lot of testing to verify how attacks were selected.

There are two phases in the fight. Each phase has a set sequence of attacks, and this sequence is advanced regardless of what action is taken by the player. When that sequence is exhausted, it picks from a smaller pool of attacks at random. This continues infinitely until you attack sans enough to advance to the next phase.

I think you should try the "practice mode". In practice mode, each attack is thrown at you in the same order as normal mode, and your HP resets between attacks. If you take too much damage, the attack starts over.
