### ISSUE TITLE
Inaccurate Colors

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#154]
Colors such as Blue Bone and Blue Heart and Orange Bone are inaccurate to the original game.
![image](https://github.com/Jcw87/c2-sans-fight/assets/58735494/8a4ec7d2-314d-4f6b-a344-7f7b6d6887a3)
This is just an example.

**Comment by Jcw87** [comment]
I've fixed the blue heart color, but there is nothing wrong with the blue bones.
![UndertaleColors](https://github.com/Jcw87/c2-sans-fight/assets/975426/95740bf0-2f4c-4d34-a908-aac4cabe535f)
I took the above screenshot today. The color picker for this image shows (20, 169, **255**).

The tint effect in Construct 2 accepts percentages, so the color must be converted.

R = 20/255 = 0.07843137254901960784313725490196
G = 169/255 = 0.66274509803921568627450980392157
B = 255/255 = 1
![EditorTint](https://github.com/Jcw87/c2-sans-fight/assets/975426/57cc1da9-c880-4a73-adcf-37c5e0b4dc14)

And the final result in Bad Time Simulator
![BTSColors](https://github.com/Jcw87/c2-sans-fight/assets/975426/6047d4a9-a4c9-44d6-9d3b-689901a231c0)
The color picker shows the same result.

**Comment by iKNIFEu** [comment]
This may be closed, but why not use float() with the Tint effect? It works.
Something like float(255/2.55) works, and I've tested it with a color picker, it's 100% accurate.

**Comment by Jcw87** [comment]
Yes, I could do that. But it works either way, and it isn't broken. This project isn't my focus right now, so fixing things that aren't broken wouldn't be a good use of my time.
