### ISSUE TITLE
[Enhancement] Add mobile support

### ISSUE THREAD

**Issue by ElijahZAwesome** [Jcw87/c2-sans-fight#17]
Me and a bunch of my friends would like this game to support mobile. I hear C2 can easily add a touch gamepad, but I don't know for sure. So you can beat Sans on the go!

**Comment by Jcw87** [comment]
I've thought about touch controls before, but I decided that it probably wouldn't be worth it. On-screen controllers tend to be terrible in any game where quick actions are necessary, so I don't think it would be a good fit for the Sans fight. If there's enough demand for it though, I might add it anyway.

The game does support real controllers, so if you can connect one to your phone, it will probably work.

**Comment by ElijahZAwesome** [comment]
I'd be cool if you added it so that it only shows up on mobile devices, even if its just for fun. I agree that it will not be the best to control, but it would be fun just to have.

**Comment by Jcw87** [comment]
Ok, you got your wish. Enjoy your pain.

**Comment by ElijahZAwesome** [comment]
I hate to open this again, but I beat him on my fifth try, it wasn't all that hard. So I guess I'm a masocist.
