### ISSUE TITLE
Framerate strikes again

### ISSUE THREAD

**Issue by OffifialMITX** [Jcw87/c2-sans-fight#19]
(I'll take it down immediately because it's much more like a problem of my computer (speed) then of the code.)

Couldn't record for a long time but finally - [this bug](https://drive.google.com/open?id=0B8HcTODSY2XzYUtQUFhZYVJUV2M) appears especially in the final attack.

**Comment by Jcw87** [comment]
Framerate isn't the only factor here. The hitboxes (which I mentioned in the 'Known Issues' part of the readme) contribute to this too.

**Comment by OffifialMITX** [comment]
I know that's a factor too, but for me it looks like this only happens because one frame has been not rendered. Sometime when in the final attack the framerate drops (for no actual reason, it just does) the heart can fly through the wavy attack bacause of that, so yes, if there's a larger hit box it should actually solve the problem.
