### ISSUE TITLE
Well I am stuck

### ISSUE THREAD

**Issue by jemfreyer** [Jcw87/c2-sans-fight#20]
This might be my fault but HOLY HELL this is annoying. I know you are doing your best but the fight froze upon completing the first attack. I can still move the soul but it sucks.
![screenshot 2017-05-08 at 9 21 59 am](https://cloud.githubusercontent.com/assets/24530023/25808560/1a662b6c-33d0-11e7-9483-f7cf2f3a354a.png)
![screenshot 2017-05-08 at 9 21 54 am](https://cloud.githubusercontent.com/assets/24530023/25808563/1df49d22-33d0-11e7-8b33-b93e10ca39e2.png)
![screenshot 2017-05-08 at 9 21 57 am](https://cloud.githubusercontent.com/assets/24530023/25808568/212089a2-33d0-11e7-8f24-8265a8321816.png)

**Comment by Jcw87** [comment]
I guess you've never played Undertale before.
'Z' is your RPG accept button.
'X' is your RPG cancel button.

Press 'Z' to continue a text prompt and to make menu selections.
