### ISSUE TITLE
Sound distortion

### ISSUE THREAD

**Issue by Sansical** [Jcw87/c2-sans-fight#3]
I was playing this and I was having trouble staying alive, so I took extra turns healing. But as the turns progressed I realized that all of the sound in the game was getting more and more distorted, so I continued to play, and after a few turns the sound was nothing but a bunch of BEEPS. (This includes the music). Please fix this.

**Comment by Jcw87** [comment]
I've seen a few comments on reddit about this, but I've never seen it happen myself. So, lets start with the basics. What operating system and web browser were you using? Is your browser up to date? Are your audio drivers up to date?

**Comment by Sansical** [comment]
Well, I own pretty much every single good and used web browser. So after this message I went ahead and tried it on all of the web browsers: Chrome, Firefox, Internet Explorer, Safari... All of them showed this sound error, even on other computers entirely. If you want this to happen, then you have to stall Sans on phase 2, the cuts when his attacks change distort the audio more everytime, so in short, if you want to experience this yourself, then stall sans during phase 2.

**Comment by Jcw87** [comment]
I've tested phase 2 extensively on a Windows 7-64 bit machine when I initially developed this game, and had no issues with the (as Toby Fox calls it) "cinematic cut" sound effect. I've also tested it extensively on a Windows 10 64-bit machine, also without issue. So, if you want me to reproduce this and fix it, you are gonna need to answer my other questions.

What operating systems did you test this on? Windows? Linux? Mac? If Windows, what version? If Linux, what distribution? If Mac, I can't really help you, but tell me what version anyway. 32-bit or 64-bit?

What versions of Firefox and Chrome did you use? 32-bit or 64-bit? You can find out by using the help menu in each. and selecting 'about'. This also has the side-effect of updating the browser if an update is available.

I'm not really interested in what happens in Internet Explorer or Safari, as [**they don't support ogg vorbis**](https://www.scirra.com/blog/46/more-on-html5-audio-codecs-and-politics).

**Comment by Sansical** [comment]
My operating system is Windows 8.1. My chrome version is 50.0.2661.102 (32-bit). I'm not sure about my Firefox version. I'll check it after I finish writing this comment. Some additional information that might not have been apparent at first: The sound error happens whenever Sans uses the multi attacks in the game, or at least that's the only times for me when the sound is getting worse. Hope this helps.

**Comment by Sansical** [comment]
Alright so apparently I was not using the latest version of Firefox and that is why it showed the error. But on Chrome, the problem persists, on chrome the cut sound is completely unused for some reason, and it now appears to be the ONLY browser showing the problem. I don't know why, but the good news is that Firefox is no longer an issue.

**Comment by Sansical** [comment]
Actually now that I think about it, A LOT of tiny sounds is cut completely from Chrome.

**Comment by Jcw87** [comment]
Fixed. 29e15cd95ccd24c8b91596dfd3601cd7b7e49c3a

I also added the ability to choose your bad time [via a link](http://jcw87.github.io/c2-sans-fight/?mode=single&attack=sans_multi3).
