### ISSUE TITLE
Full Custom Fights?

### ISSUE THREAD

**Issue by BloomChara** [Jcw87/c2-sans-fight#30]
I was messing with custom attacks and found i can make the menu bones pop up. I thought to myself "hey, what if i can make a full custom battle?" I then went and tried to get the menu to pop up, which i was unable to do. I was wondering if there is, or will be, any way to make full battles? possibly with custom healing items.

**Comment by Jcw87** [comment]
There are some functions which, while callable from attacks, aren't meant to be called from attacks. This includes the functions that enable menu bones.

There isn't enough "additional functionality" to do anything super useful. It really is just meant for alternate Sans attacks.

**Comment by HeyHeyPizza111** [comment]
this does seem a pretty cool idea
