### ISSUE TITLE
Auto Jump Feature?

### ISSUE THREAD

**Issue by TheTeleportingFish** [Jcw87/c2-sans-fight#31]
I've noticed that in Undertale there is an auto jump feature for the blue heart state, which is important for the slam attack that sans does. Heres an example, Im holding down the up key most of the time as you can see. 

![2017-06-24 23-33-49](https://user-images.githubusercontent.com/20102267/27513536-b1bb87dc-5937-11e7-9e7c-5645c9eb4e63.gif) 

I was thinking you didn't notice this so I'm just going to point it out so you can add it...

**Comment by Jcw87** [comment]
Duplicate of #5
