### ISSUE TITLE
Bonestab3 attack isn't accurate to game.

### ISSUE THREAD

**Issue by FawfulBeanish** [Jcw87/c2-sans-fight#32]
I replayed sans on vanilla Undertale and I can definitely say that the third bonestab attack was a lot different. Since I don't know how I would get footage of this, here's just two videos of vanilla sans and the simulator running the same attack with links that put you to where those attacks appear.

OG: https://youtu.be/Vr4IYjeplJA?t=386
Simulator: https://youtu.be/sG17kWBYzzk?t=243

**Comment by Jcw87** [comment]
The only significant difference I see is that the original's red outline doesn't actually align with where the bones end up. Not only does my version make more sense, it's less of a pain to do it that way.
