### ISSUE TITLE
Blue SOUL

### ISSUE THREAD

**Issue by ZackN** [Jcw87/c2-sans-fight#4]
First, when you select FIGHT, ACT, ITEM, or SPARE, the blue SOUL is supposed to be slightly lower, and fall when you select. Second of all, when you let go of up or the blue SOUL reaches the peak of the jump, you have a split-second float time. Finally, on the green platforms going left attack, I keep falling through the second-to-last platform.

**Comment by Jcw87** [comment]
1. Something being off by a few pixels doesn't concern me, unless it affects the gameplay.
2. I'm aware that the jumping behavior isn't correct. I need exact figures. In a 30fps game like Undertale, there's 29 different time values that could be described as 'split second'. 'split-second' isn't useful.
3. Show me a video of falling through the platform.

**Comment by srb2thepast** [comment]
Actually the same thing happens to me i just Saw The soul FALL Through the
platform and I was flying all over the screen.

**Comment by HuntertheWhale** [comment]
I didnt have that happen to me

**Comment by OffifialMITX** [comment]
When you jump on a moving platform while pressing an arrow the heart stops moving until the platform contact is lost and you simply fall down. I'll try to make a video about it.

**Comment by OffifialMITX** [comment]
I was wrong - it take generally a while until the heart starts moving among the platform.

**Comment by OffifialMITX** [comment]
[Here](https://drive.google.com/file/d/0B8HcTODSY2XzbTZqc1FheXNNa1k/view?usp=sharing), If you take a closer look, you'll notice that after falling on the platform (I don't press anything) the heart takes a before moving.

**Comment by OffifialMITX** [comment]
> Show me a video of falling through the platform.

[Here](https://drive.google.com/file/d/0B8HcTODSY2XzWWZBT2I4MXNUVm8/view?usp=sharing).

**Comment by Jcw87** [comment]
> [Here](https://drive.google.com/file/d/0B8HcTODSY2XzbTZqc1FheXNNa1k/view?usp=sharing), If you take a closer look, you'll notice that after falling on the platform (I don't press anything) the heart takes a before moving.

This appears to be caused by running at lower framerates. I changed something that might improve this. If this is still a problem, open a new issue.

> [Here](https://drive.google.com/file/d/0B8HcTODSY2XzWWZBT2I4MXNUVm8/view?usp=sharing).

That video is really helpful. It demonstrates that the problem is caused by overlapping a second platform. This should now be fixed.

**Comment by OffifialMITX** [comment]
Yes, now it works (finally first part no hit:)
