### ISSUE TITLE
Problem with Custom Attacks

### ISSUE THREAD

**Issue by Cuddelz** [Jcw87/c2-sans-fight#41]
I can imagine this is a pretty hard thing to fix, but I wouldn't know since I don't use Construct 2 to make games. Every time I try to execute a .csv in the Custom Attacks section, you know, like press the Run Attack button, the page just kind of... Stops... What I mean is I can't do anything, not move the heart selection up or down, select or deselect, and the very beginning of the song, like the first note, just plays on an earrapey loop. Now, after trying to load and run the attack on one of the browsers that aren't supported, Mozilla Firefox, it worked like a charm. I guess this is just a problem with Chrome, in which case, please try to find a fix.

**Comment by Jcw87** [comment]
I loaded an attack on the latest chrome and had no issues. Make sure you are using the latest chrome, and try disabling any extensions you may have.

**Comment by Cuddelz** [comment]
I did just that, and still had the same problem. Mayhaps it's just the attack. I was trying to load the Welcome To Hell Demo custom attack, which you did not make, but rather a fan. Yeah, I think that's the problem.

**Comment by Sam1370** [comment]
+1 can reproduce

**Comment by Jcw87** [comment]
If you want me to investigate this any further, you will need to provide a link to the attack that isn't working.

**Comment by Sam1370** [comment]
https://drive.google.com/file/d/0BxqP43x0cMvqOTNnY3RTVzh3ZGs/view
Welcome to Hell custom attack

(also, just google it???)

**Comment by Jcw87** [comment]
For starters, the attack is improperly using the Sound function to play the music. The Music function exists for a reason. The key difference is that sounds are played through the web audio API and must be fully loaded before they can be played, where as music is played through the html5 media element and is streamed. The megalovania track is internally marked as being music, and thus, should be played as music. Another difference is that sounds will change pitch when played at different speeds, where as music will not change pitch.

But that's not what is causing Chrome to freak out. What's causing Chrome to freak out is setting the playback speed to 20x. Don't do that.

It's not really my job as a developer to seek out 3rd party content that is causing an issue. Any developer will tell you to provide all of the information required to reproduce the issue, including any 3rd party content that may be related to it.

**Comment by BloomChara** [comment]
I’ll get on it soon heck
