### ISSUE TITLE
Sine Bones can only go one way.

### ISSUE THREAD

**Issue by xnossisx** [Jcw87/c2-sans-fight#42]
There isn't an option for which direction they come from.

**Comment by Jcw87** [comment]
Setting the padding to a negative number will make them come from the other side of the screen.

But why are you using it? Didn't you read the comment next to that one?

`// Created out of laziness, probably shouldn't use.`

**Comment by xnossisx** [comment]
Actually, soon after making that, I quickly realized that you could make much harder attacks if the bones didn't follow a simple pattern, so I changed it.

**Comment by xnossisx** [comment]
Oh, and just so you know, there is no such thing as colors on BoneVRepeat or BoneHRepeat.
