### ISSUE TITLE
Choose file custom attack

### ISSUE THREAD

**Issue by TexRexTex** [Jcw87/c2-sans-fight#45]
You should try to add the "autofocus" attribute to the choose file button so you can just press enter like you can for the rest of the buttons.

**Comment by iKNIFEu** [comment]
Yeah probably, but in construct 2, I believe there is no way, but you just have to click.
Idk maybe I'm too dumb to know how I can do that lol

**Comment by TexRexTex** [comment]
Is This even made in construct? btw some of the other options have auto focus but not the choose file input. lol I made that issue 2 years ago.

**Comment by TheBesterCode** [comment]
@TexRexTex  I think I can make some js things, let me try

**Comment by iKNIFEu** [comment]
@TheBesterCode Good luck.
I'm really bad at js so yeah lol

**Comment by TheBesterCode** [comment]
Here you are #69

**Comment by Jcw87** [comment]
The above PR has been merged.
