### ISSUE TITLE
Sans Bad Time Simulator

### ISSUE THREAD

**Issue by TBNRBoom** [Jcw87/c2-sans-fight#46]
I noticed that in the actual sans battle in undertale, the blue bones don't seem to actually do damage to the character, but I'm not entirely sure. In the simulator, the blue bone attacks from sans actually do damage to the character, but you cannot dodge or evade the blue bones, so it is inevitable that they will hit you and hurt the you. I believe this is an issue, but I'm not sure, so please respond!

**Comment by Jcw87** [comment]
I based the simulator on recordings of my own attempts at the sans fight. Here's a video of my first attempt.

https://youtu.be/VDeg8dl9Lec?t=113

As you can see from the video, the blue bones do in fact damage you in the original game.

It is also possible to get through the attack in my version without taking damage, so I'm not seeing a problem here. I'm sure the blue bones register a little differently in mine (maybe it's 60fps related), but it's close enough

**Comment by DebugMC** [comment]
Blue bones ONLY damage you if you are MOVING. Orange bones are the opposite, and only hurt you if you don't move.

**Comment by Dukemz** [comment]
If you stay still, then the blue bones don't damage you.
