### ISSUE TITLE
Xbox stuff

### ISSUE THREAD

**Issue by AsrielWasTaken** [Jcw87/c2-sans-fight#47]
On Microsoft Edge theres no sound and the Xbox analogic controls are too bad..

**Comment by Jcw87** [comment]
I just fixed the "bad controls", no thanks to you. This could have been fixed when you reported it. All you had to do was use your words to describe the problem. "Moving the left stick down causes the heart to move down and right". It's that easy!

**Comment by iKNIFEu** [comment]
> I just fixed the "bad controls", no thanks to you. This could have been fixed when you reported it. All you had to do was use your words to describe the problem. "Moving the left stick down causes the heart to move down and right". It's that easy!

Thank you!
I can now play on my phone easily.
