### ISSUE TITLE
Moving Platform Doesn't Carry

### ISSUE THREAD

**Issue by MetaNite64** [Jcw87/c2-sans-fight#54]
On the sans_platforms2 attack, all the moving platforms except the 6th platform you usually jump on carry you in their direction. The 6th platform will occasionally just slide out from under you, and you will fall in the bone-sea below. I have video proof, but can't attach it (github comments don't support video files).

**Comment by Jcw87** [comment]
You can still post links on GitHub, and there's a variety of places that you can upload your video to. YouTube is one of the easiest. Just upload an unlisted video.

**Comment by Mario253** [comment]
Here's the [video](https://youtu.be/EVf-Xo7ohvA).

**Comment by ChaboCode** [comment]
I think I can do sem things. Let me try

**Comment by Jcw87** [comment]
Fixed
