### ISSUE TITLE
Infinite loop detection threshold too low?

### ISSUE THREAD

**Issue by gotoAndDie** [Jcw87/c2-sans-fight#6]
I'm not sure if the current threshold serves any particular purpose, but right now, it is quite limiting. In fact, increasing the amount of bones in the wavy bones in the final attack by a few already pushes it past the limit, and the line number given is all over the place, as well. The engine is actually quite capable of pushing a lot more loops; after hacking at the function that stops the attack when an infinite loop occurs, I tried plotting a simple bifurcation diagram from 2.8 to 3.2 step 0.02 using small bones. It actually works - with an outside loop that runs 20 times and an inside loop that loops 95 times to converge to the needed values.

So, uh, increase it maybe? So that custom attacks can be more complex and stuff?

**Comment by Jcw87** [comment]
It is most certainly capable of running for longer. But, debugging it when it's stuck in an infinite loop is a pain in the ass, so I had to put a limit on. The current threshold is an arbitrary number I picked that works for the attacks I needed to make. How much bigger do you need it? Keep in mind, the counter resets to zero when the game is allowed to render a single frame.
