### ISSUE TITLE
Bones are all the same.

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#64]
I know you may not understand this, but-- in the actual fight, there are different bones.
in sans_platforms3, there is a different bone in the middle one, a bone that doesn't have a bottom bone thing (I don't know the term, sorry), the same thing goes for the bottom part of sans_platforms1, in sans_bonegap1, the bones look like this:
![image](https://user-images.githubusercontent.com/58735494/79006822-3eda7a00-7b5a-11ea-888a-01ef4a61775f.png)
The same thing goes for sans_platforms1 (where, in the top part of the combatzone, in the final part, where sans puts 3 small bones in the top, and then a tall bone rushing to get you in the end, they look like the bones in sans_bonegap1).

I know it's a lot to take in, but that may be an issue, and you forgot that it exists.
Thank you.

**Comment by Jcw87** [comment]
I've been busy with the new Animal Crossing game, so I don't currently have the drive to investigate this. If you could provide comparison screenshots of my version vs the real game, that might help me tell you why it's different. Most of these differences are things that I chose to do for one reason or another. I made this years ago, so while I may not recall exactly why I made a particular decision back then, the reason might have been "I think it looks better this way".

For instance, the original bones aren't actually symmetrical, but they are in my version, and that was 100% because I think it looks better.

**Comment by iKNIFEu** [comment]
Alright, I'll have to agree with you, this is NOT my game, I can make my own bad time simulator mod that has these features, while you, you can do what you want in your game. Thank you for replying :)

**Comment by iKNIFEu** [comment]
There are 3 types of bones Sans uses (I don't mean the BoneStabs, I'm talking about what they look like.)
This, which is mostly used in attacks like BoneGap1, and BlueBone, and many others:
![image](https://github.com/Jcw87/c2-sans-fight/assets/58735494/ed86260e-4f3f-4499-b01a-9bf368454ffb)
This one is mostly used in attacks that has a bone floor, like the platform attacks:
![image](https://github.com/Jcw87/c2-sans-fight/assets/58735494/56ac8022-4ee2-451c-bba2-9f9a1afcd122)
I don't remember when this is mostly used, however I do remember that it is used in platform4 and platform4_hard in the gaps:
![image](https://github.com/Jcw87/c2-sans-fight/assets/58735494/17e5372e-3bd2-49d7-95a3-545c4e0f3bf2)

Hopefully I made everything clear.

**Comment by Jcw87** [comment]
I never liked how the "bone with only one end" looked in the platforms3 attack, so I changed it intentionally. It would have been more work to make it look that way anyway. Why put in the extra effort for something I don't even like?

The lower bones in the platforms4 attack are full bones, but the bottoms are clipped by the same blending effect that prevents most attacks from being visible outside of the combat zone.

**Comment by iKNIFEu** [comment]
This is irrelevant, but what do you mean by "not planned"? Does that mean you won't do this, or you won't fix it, or you may add it in the future but it is currently not planned right now?

**Comment by Jcw87** [comment]
Github gives me two options, close as completed, or close as not planned. It's certainly not completed, since I am not implementing the changes, so I picked the other one. I'm **not planning** on implementing this.

**Comment by Jcw87** [comment]
> And I forgot to mention, you didn't say anything about the first type of bone, which is this: ![image](https://user-images.githubusercontent.com/58735494/257399395-febbd71b-03ae-42ad-b686-53d8d7289652.png) You may not like the bone with no end, but why not add the first type of bone? It can make the simulator more accurate to the original game, and for some reason, it fits. Though it make take a little while to add it into the attacks, especially while this project is not your current focus.

> For instance, the original bones aren't actually symmetrical, but they are in my version, and that was 100% because I think it looks better.

Personally, I think that Toby wanted to make the bones symmetrical. I think one of the existing bone sprites is. However, the resizable bones use a gamemaker line drawing function to connect 2 ends together, and I think he had issues getting that perfectly symmetrical, and settled for what you see in the final game.
