### ISSUE TITLE
I'm confused with custom attacks.

### ISSUE THREAD

**Issue by HuntertheWhale** [Jcw87/c2-sans-fight#7]
You **Need** to make a command list and tutorial option for how to make a custom attack for this game

**Comment by Jcw87** [comment]
Actually, I don't **need** to do anything. I made this in my free time blah blah standard lecture blah blah.

That being said, it IS on my todo list. It's just a matter of getting around to it.

**Comment by HuntertheWhale** [comment]
sorry then

**Comment by HuntertheWhale** [comment]
i just couldnt find a way to get any lines or how-tos on making a custom attack

**Comment by HuntertheWhale** [comment]
either way, I could just ask if you can tell me how

**Comment by Deathfang99** [comment]
I'm going to make a YouTube video on custom attacks, and how to make them. I will link it here when its out

**Comment by HuntertheWhale** [comment]
are u gonna send it or what
