### ISSUE TITLE
Problem with modding BTS

### ISSUE THREAD

**Issue by DeltaCC** [Jcw87/c2-sans-fight#76]
When I try to replace the texture of the Blaster / bone, it is as if it is replaced but nothing changes in the game, the same textures.
Help pls

**Comment by ChaboCode** [comment]
Where are you changing the texture? And where are you playing the game with the modified texture?

**Comment by Awfull-DEV** [comment]
> Where are you changing the texture? And where are you playing the game with the modified texture?

I changing blaster texture in folder "images" (gasterblaster-sheet0, gasterblaster-sheet1) 
awfull-dev.github.io/double-deuce/ Yes, it does not differ from the original, but this is because almost everything I did-did not apply, only the music changed

**Comment by Awfull-DEV** [comment]
> Where are you changing the texture? And where are you playing the game with the modified texture?

Maybe I'm doing something wrong. I started doing this 3 days ago

**Comment by ChaboCode** [comment]
I cloned your project on the last commit, and I couldn't find any "images" folder. WH=here are you saving your textures?

**Comment by ChaboCode** [comment]
I got something. The problem with the bones is that you only changed BoneSTabH, wich is the texture shown when a BoneStab attack ocours, But the BoneH, the BoneV and the BoneStabV have the default texture. Try changing it.

**Comment by Awfull-DEV** [comment]
> I cloned your project on the last commit, and I couldn't find any "images" folder. Where are you saving your textures?

images folder in gh-pages. Anyway, thanks for help

**Comment by Awfull-DEV** [comment]
> I got something. The problem with the bones is that you only changed BoneSTabH, wich is the texture shown when a BoneStab attack ocours, But the BoneH, the BoneV and the BoneStabV have the default texture. Try changing it.

I change the BoneH, BoneV, BoneStabV. But its still have original texture

**Comment by ChaboCode** [comment]
The preview of Construct changes the texture, maybe is semthing wrong with the deploy version.

**Comment by ChaboCode** [comment]
The preview also render Sans disassembled lol you should check that

**Comment by Awfull-DEV** [comment]
> The preview also render Sans disassembled, you should check that



> The preview of Construct changes the texture, maybe is semthing wrong with the deploy version.

It's possibly to fix?

**Comment by ChaboCode** [comment]
You have two files for the same bone: BoneH.png and boneh.png. The original code is grabbing the boneh.png texture, in order to fix that you should rename the purple bones to purplebone*.png, or if you dont want to use the white ones you should rename all the CamelCase images to downcase

**Comment by ChaboCode** [comment]
> You have two files for the same bone: BoneH.png and boneh.png. The original code is grabbing the boneh.png texture, in order to fix that you should rename the purple bones to purplebone*.png, or if you dont want to use the white ones you should rename all the CamelCase images to downcase

also rename the images on the project, otherwise it may fail by searching the CamelCase images.

**Comment by iKNIFEu** [comment]
Actually no.
I think you should change the image while construct 2 is closed.
if you do that while construct 2 is open, the file will stay as it is, as from my experience, it's literally annoying.

**Comment by Jcw87** [comment]
Actually, both of you are wrong, because if you were paying attention, the OP is trying to change the images in the compiled project, likely because they don't own Construct 2. Also, fun fact that is only slightly relevant. When a Construct 2 project is open, regardless of whether it is a folder project or a *.capx, the editor works with a folder somewhere in your AppData folder. As a result, changing images in your project folder while the editor has it open will never work. I wouldn't recommend trying to tamper with this AppData folder either, as it can cause weird visual issues in the editor and possibly crash it.

**Comment by iKNIFEu** [comment]
I do own construct 2.
Maybe I'm just really not paying attention.
Well, thank you.

**Comment by iKNIFEu** [comment]
I do own construct 2.
Maybe I'm just really not paying attention.
Well, thank you.
