### ISSUE TITLE
Add the spare sans ending.

### ISSUE THREAD

**Issue by CrappySalami** [Jcw87/c2-sans-fight#8]
I know that this isn't really an issue, (tbh I love your game.) but I totally think you should add the spare ending. I mean a good reason not to add this is because of spoilers. But I'd think that it'd be really fun if that ever got implemented. But still, I **Under**stand, you're a busy guy, and I don't expect you to HAVE to do this. Thanks.

**_geeeeeeeettt duuuuuuunnkked on!!!!!!_**

**Comment by Jcw87** [comment]
IMO, some details of the fight should be reserved for the real thing. This is one of those details. My version was only ever meant to help you practice for the real fight (or just find out if you could beat him).

**Comment by CrappySalami** [comment]
Okay. Thank you for your response.
