### ISSUE TITLE
Did the Web game has Develement Docs?

### ISSUE THREAD

**Issue by helloworldSB** [Jcw87/c2-sans-fight#85]
Your website is really excellent.
But, you know, it is difficult for newbies like us to write custom sans battles. Although there are some excellent custom ATTAKs online, most of them are so complicated that it is difficult for us to learn from them. Is there any documentation about customizing ATTAK?
 thank!

-----
I am using google translate

11-27
-----
I know that there is already a help document here, but even with a top-notch translator, it is difficult for us to understand
So we urgently need a Chinese document.

**Comment by ChaboCode** [comment]
There is a Documentation folder for custom attacks, but it is on English. Maybe you can help to translate it, or someone you know.

**Comment by helloworldSB** [comment]
> There is a Documentation folder for custom attacks, but it is on English. Maybe you can help to translate it, or someone you know.

I will try to translate it later
Thank
