### ISSUE TITLE
Slamming Sound issue

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#92]
Hmmm, you DID fix the gaster blaster sounds 5 years ago, but so far you NEVER fixed this issue!
I'm new to github so I don't know how to pull request, but if you have the time, can you add a "PlayerHurt" sound to the slam? You can play the game yourself and compare, to see the accuracy.
I understand if you won't do that, but if you're going to reply, please tell me how to make a pull request.

**Comment by Jcw87** [comment]
It never got fixed because nobody reported it.
It's fixed now.
