### ISSUE TITLE
can i use

### ISSUE THREAD

**Issue by BlueDragon92** [Jcw87/c2-sans-fight#96]
iam want make my game is it fine if i use to make gamejolt or gethub or something as long as i give credit???
please tahnk youuuu your good at these thing! :D

**Comment by iKNIFEu** [comment]
I think that's allowed, Jcw87 himself said that you CAN use his, but with different sprites, stories, attacks, and such, so everyone can find the most up to date version. That is, if you're using github to do this, but, maybe on gamejolt and stuff, I think you must credit him no matter what, so, uh... I think you can use it, but I'm not too sure about the one in gamejolt.
He will probably answer this if I'm wrong, but if I'm not wrong, he can just add the "duplicate" thing.
Good luck buddy! Have a nice day... or night.
