### ISSUE TITLE
Bluebone has the wrong color.

### ISSUE THREAD

**Issue by iKNIFEu** [Jcw87/c2-sans-fight#97]
Blue bone actual color (RGB):
Red: 0
Green: 65
Blue: 100

Orange bone actual color (RGB): {You will probably not use but ok}

Red: 100
Green: 75
Blue: 0

**Comment by ChaboCode** [comment]
lmao how precise

**Comment by iKNIFEu** [comment]
so am I correct lol

**Comment by Jcw87** [comment]
I'm gonna settle this with a lossless screenshot.
![image](https://user-images.githubusercontent.com/975426/111559083-1cc77f80-874d-11eb-9689-47a6ed611e1b.png)
The color picker in MSPaint shows these RGB values:
```
R: 20
G: 169
B: 255
```
When you scale it down from a 0-255 range to a 0-100 range, you get these numbers:
```
R: 7.843
G: 66.2745
B: 100
```
So the only thing wrong here is the red channel. The scaling is calculated by taking the MSPaint number, dividing it by 255, and then multiplying it by 100

**Comment by iKNIFEu** [comment]
Ah, alright. guess I was almost correct.
Well, guess I'll call it a day.
